server:
  port: 10010

spring:
  jms:
    template:
      default-destination:  DEV.QUEUE.1
com:
  foo:
    jms:
      simple:
        queue:
          requestReplyQueue: DEV.QUEUE.2

ibm:
  mq:
    queueManager: QM1
    channel: DEV.ADMIN.SVRCONN
    connName: localhost(1414)
    user: admin
    password: passw0rd