server:
  port: 10010

ibm:
  mq:
    queueManager: QM1
    channel: DEV.ADMIN.SVRCONN
    connName: localhost(1414)
    #    connName: 192.168.20.2(1414)
    user: admin
    password: passw0rd

spring:
  jms:
    template:
      default-destination:  DEV.QUEUE.1

com:
  foo:
    ibmmq:
      simple:
        queue: DEV.QUEUE.2
        topic: DEV.BASE.TOPIC