version: '3'
#version: '2'
services:
  ibmmq-server:
      stdin_open: true
      tty: true
      restart: always
      image: ibmcom/mq:latest
      ports:
        - "1414:1414"
        - "9443:9443"
      container_name: ibmmq-server
      environment:
        - LICENSE=accept
        - MQ_QMGR_NAME=QM1
        - MQ_APP_PASSWORD=Wh0Kno!
      volumes:
        - ibmmq-server-volume:/mnt/mqm
      networks:
        ibmmq-network:
          ipv4_address: 192.168.20.2
          aliases:
            - qmgr
volumes:
  ibmmq-server-volume:
    external: true

networks:
  ibmmq-network:
    external: true